# Generated by Django 4.2.2 on 2023-09-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="lng",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
