# Generated by Django 4.2.2 on 2023-10-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_discountcoupon_expiration_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcoupon",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
