# Generated by Django 4.2.2 on 2023-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customer_user_lat_customer_user_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
