# Generated by Django 4.2.2 on 2023-10-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
